source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
#use_frameworks!
target 'MyProject' do

pod 'AFNetworking', '~> 3.0'
pod 'FMDB', '~> 2.5'
pod 'Reachability', '~> 3.2'
pod 'Base64', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.7.2'
pod 'ImagePlayerView', '~> 1.0.3'
#pod 'MMDrawerController', '~> 0.6.0'
pod 'MJRefresh', '~> 3.0.1'
#订单等列表顶部带切换的
pod 'ZJScrollPageView', '~> 0.1.8'
#自定义AGEmojiKeyboard
pod "AGEmojiKeyboard"
pod 'HCSStarRatingView', '~> 1.4.5'
pod 'TPKeyboardAvoiding', '~> 1.3'

pod 'HMSegmentedControl'
pod 'PNChart'
#pod 'TTTAttributedLabel'
#pod 'BaiduMapKit', '~> 2.9.1'
## 主模块(必须)
#pod 'ShareSDK3'
## Mob 公共库(必须) 如果同时集成SMS—SDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
#pod 'MOBFoundation'
#
## UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#pod 'ShareSDK3/ShareSDKUI'
#
## 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
#pod 'ShareSDK3/ShareSDKPlatforms/QQ'
#pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
#pod 'ShareSDK3/ShareSDKPlatforms/WeChat'


end
